name: React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Installing deps
        run: npm ci
      - name: Building apps
        run: npm run build
  

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to GH pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist

  
    